name: Build Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: npm

      - name: remove-node-modules
        run: rm -rf node_modules package-lock.json

      - name: npm-install
        run: npm install

      - name: app-build
        run: npm run build
